const { GoogleSpreadsheet } = require('google-spreadsheet');

async function   test() {
  // Initialize the sheet - doc ID is the long id in the sheets URL
const doc = new GoogleSpreadsheet('1H6AxJjno5aeDqKH5fZLHKtSukS-8-f4vh8U44x1Dp0E');

await doc.useServiceAccountAuth({
  // env var values are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  client_email: "nativepromoters@gmail.com",
  private_key: "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",
});

await doc.loadInfo(); // loads document properties and worksheets
console.log(doc.title);
}
test();